---
language: cpp
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - gcc-avr
      - binutils-avr
      - avr-libc
env:
  - CC=gcc-8 && CXX=g++-8
before_install:
  - sudo apt-get update -qq
install:
  - make get-deps
script:
  - cmake .
  - make hex